version: "3.7"

services:
    database_fortbrinq:
        image: postgres
        container_name: budget-api
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_CONNECTION}
        volumes:
            - pgdata:/data/postgres
volumes:
    pgdata:
        driver: local