version: "3.7"

services:
    database:
        image: postgres
        container_name: budget_api
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=postgres
        volumes:
            - pgdata:/data/postgres
volumes:
    pgdata:
        driver: local