version: "3.7"

services:
    database:
        image: postgres
        container_name: budget_api
        restart: always
        ports:
            # change the port here and env when return an error as:
            # exposing port TCP 0.0.0.0:5432 -> 0.0.0.0:0: listen tcp 0.0.0.0:5432: bind: address already in use
            - 5444:5432
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=database_budget_api
        volumes:
            - pgdata:/data/postgres

    app:
        build: 
           context: .
        container_name: budget_api_app
        restart: always
        working_dir: /usr/app/src
        ports:
            - 3033:3033
        volumes:
            - ./src:/usr/app/src
        links:
            - database
        depends_on:
            - database
volumes:
    pgdata:
        driver: local
