version: "3.7"

services:
    database:
        image: postgres
        container_name: user_auth
        restart: always
        ports:
            - 5430:5432
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=database_user_auth
        volumes:
            - pgdata:/data/postgres

    app:
        build: 
           context: .
        container_name: user_auth_app
        restart: always
        working_dir: /usr/app/src
        ports:
            - 3033:3033
        volumes:
            - ./src:/usr/app/src
        links:
            - database
        depends_on:
            - database
volumes:
    pgdata:
        driver: local
