version: "3.7"

services:
    database:
        image: postgres
        container_name: database_budget_api
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=fortbrinq
            - POSTGRES_PASSWORD=fortbrinq
            - POSTGRES_DB=budget_api
        volumes:
            - pgdata:/data/postgres

    app:
        build: .
        container_name: budget_api
        restart: always
        ports:
            - 3333:3333
        volumes:
            - .:/usr/app
        links:
            - database
        depends_on:
            - database
volumes:
    pgdata:
        driver: local
