version: "3.7"

services:
    database:
        image: postgres
        container_name: budget-api
        restart: always
        ports:
            # change the port here and env when return an error as:
            # exposing port TCP 0.0.0.0:5432 -> 0.0.0.0:0: listen tcp 0.0.0.0:5432: bind: address already in use
            - 5432:5432
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_CONNECTION}
        volumes:
            - pgdata:/data/postgres
        env_file: .env
    app:
        build: 
           context: .
        container_name: budget_api_app
        restart: always
        working_dir: /usr/app/src
        ports:
            - 3033:3033
        volumes:
            - ./src:/usr/app/src
        links:
            - database
        depends_on:
            - database
volumes:
    pgdata:
        driver: local
